package oop;

public enum Genre {
	
	ART, BIOGRAPHY, BUSINESS, CHICK_LIT, CHILDRENS, CHRISTIAN, CLASSICS, COMICS, CONTEMPORARY, COOKBOOKS, CRIME, EBOOKS, 
	FANTASY, FICTION, GAY_AND_LESBIAN, GRAPHIC_NOVELS, HISTORICAL_FICTION, HISTORY_HORROR, HUMOR_AND_COMEDY, MANGA, 
	MEMOIR, MUSIC, MYSTERY, NONFICTION, PARANORMAL, PHILOSOPHY, POETRY, PSYCHOLOGY, RELIGION, ROMANCE, SCIENCE, 
	SCIENCE_FICTION, SELF_HELP, SUSPENSE, SPIRITUALITY, SPORTS, THRILLER, TRAVEL, TOUNG_ADULT

}
